### ISSUE TITLE
[不能用，报错] vite.config.js moment 配置没有删除干净

### ISSUE THREAD

**Issue by transtone** [nekocode/antd-dayjs-vite-plugin#1]
```cmd
Error: ENOENT: no such file or directory, open 'dayjs/dist/locale/zh-cn'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
```

正确的路径应该是  `dayjs/locale/zh-cn`

**Comment by nekocode** [comment]
@transtone 可以提供能复现的工程么？这个库目前并没有用到 `dayjs/dist/locale/zh-cn` 这个路径啊。

**Comment by transtone** [comment]
sorry, vite.config.js 还有遗留的 moment 配置导致的。
